# Site settings
title: Sean O'Toole
email: sean.otoole@seanotoole.net
description: "This site is hosted by Github.com"
baseurl: ""
url: "http://seanotoole.net"
username: "seanot"

# Build settings
markdown: kramdown
permalink: pretty
