# Site settings
title: Sean O'Toole
email: sean.otoole@seanotoole.net
description: "Ramblings on programming and life"
baseurl: ""
url: "http://seanotoole.net"
username: "seanot"

# Build settings
markdown: kramdown
permalink: pretty


# gems to be loded on github
gems:
  - jekyll-sitemap
